os: linux
dist: bionic
language: shell

services:
  - docker

git:
  submodules: true

env:
  - DOCKER_FILE=docker/centos-7/Dockerfile
  - DOCKER_FILE=docker/centos-8/Dockerfile
  - DOCKER_FILE=docker/fedora-31/Dockerfile
  - DOCKER_FILE=docker/ubuntu-16.04-lts/Dockerfile
  - DOCKER_FILE=docker/ubuntu-18.04-lts/Dockerfile
  - DOCKER_FILE=docker/ubuntu-19.10/Dockerfile
  - DOCKER_FILE=docker/ubuntu-20.04-lts/Dockerfile

before_install:
  - docker build --rm -f ${DOCKER_FILE} --build-arg RUNUID=$UID -t ikforth-build:latest .
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "scons -c linux all && scons -c win32 all"

script:
  - export GIT_DESC=`git describe --tags --always --abbrev=8`
  - export BUILD_TAG=${TRAVIS_TAG:-${GIT_DESC}}
  - ./docker/build-ci.sh

deploy:
  provider: releases
  api_key:
    secure: QypaNVwnMk6vl+ahdOwrI0atse4+gjcE7dc0Ap4f+kFxXDdb+nAVEAAjuB1qrhOHef4lBcL9yNQwKQcJTPwc4BM0535jgVCjdvYdTO1lEzDzU936YWhZihW4/OLCvKWdHET5Vqh5mfSasbafCPg96lRTg0jupMYt9c2+YvvXQjwbdTv5p2EKfJ4l7xHRZbV3sI6TDFA2Ik9ar08DZENQorK75arx+Pp2wJM57Aqlqh/VXNlrBoTGqv4lNDQsKw5+qsi8/xdPs7nb6fjSeWk9N2dxhWxvOiFX6h8GySiD7b1E5XqfuAd7BENbRCrj1SzqW8UTJ1PR9AG9MkcpdQvu0E2kUvn0CW/3sGTnBbBGuc0/dbyZI/w41DokR+iZZxm/fA/lcL8KYj5KcvNMUvvIM+0dvLM1PJGEe8MxTXy83gWR8LFfXrYHlub0PGFb8oX1Vusp0vZGbGdt4qw1WnbDff/jOVZBbWMPk2/A0qk1iJO1uFXTueIARF+z7c0swuezyRvB66YkfXLMCvJEO58y0E/3dcWV1yfpg1CB7ePqN5VMaT+Il71nB9o4CwQMf5pMK/EDbZll3bk6BQzrKW7JbwIbuNYCFjFlfRExVJKYjzM36kmMSuppiGwZngUxqhio519/jN0tSrrHfx1/vCFnwYuEkQxBp1SKx1YeR5/U3fw=
  file:
    - build/ikforth-dist-${BUILD_TAG}.tar.gz
    - build/ikforth-dist-${BUILD_TAG}.zip
  skip_cleanup: true
  on:
    condition: -f build/ikforth-dist-${BUILD_TAG}.tar.gz
    condition: -f build/ikforth-dist-${BUILD_TAG}.zip
    tags: true
