os: linux
dist: bionic
language: shell

services:
  - docker

git:
  submodules: true

env:
  - DOCKER_FILE=Dockerfile
  - DOCKER_FILE=Dockerfile.centos8
  - DOCKER_FILE=Dockerfile.ubuntu1604

before_install:
  - docker build --rm -f ${DOCKER_FILE} --build-arg RUNUID=$UID -t ikforth-build:latest .
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "scons -c"

script:
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "echo -e '123\n ' | scons itc ansitest"
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "echo -e '123\n ' | scons dtc ansitest"
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "echo -e 'bye\n ' | scons fptest"
