os: linux
dist: bionic
language: shell

services:
  - docker

git:
  submodules: true

env:
  - DOCKER_FILE=docker/Dockerfile
  - DOCKER_FILE=docker/Dockerfile.centos8
  - DOCKER_FILE=docker/Dockerfile.fedora33
  - DOCKER_FILE=docker/Dockerfile.ubuntu1604
  - DOCKER_FILE=docker/Dockerfile.ubuntu1804
  - DOCKER_FILE=docker/Dockerfile.ubuntu1910

before_install:
  - docker build --rm -f ${DOCKER_FILE} --build-arg RUNUID=$UID -t ikforth-build:latest .
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "scons -c"

script:
  - ./docker/build-ci.sh
