sudo: required

language: forth

services:
  - docker

before_install:
  - docker build --rm -f Dockerfile --build-arg RUNUID=$UID -t ikforth-build:latest .
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "scons -c"

env:
  - ANSITEST_CMD="echo -e '123\n ' | scons itc ansitest | tee build/ansitest-itc.out"
  - ANSITEST_CMD="echo -e '123\n ' | scons dtc ansitest | tee build/ansitest-dtc.out"

script:
  - docker run --rm -it -v $PWD:/opt/ikforth ikforth-build:latest -c "${ANSITEST_CMD}"
